CA-33362,CA-33361: vif hotplug: Handle tap network devices via the hotplug mechanism
Replaces call to /etc/xen/qemu-ifup.

As part of this it was necessary to ensure that the tapX.Y device name
exactly matches the vifX.Y device name, otherwise and domain with only
non-zero VIF.device's would not be correctly constructed.

Causes tapX.Y to get address FE:FF:FF:FF:FF:FF (CA-33361) as a side effect.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>

diff --git a/scripts/vif b/scripts/vif
--- a/scripts/vif
+++ b/scripts/vif
@@ -20,24 +20,16 @@
 
 # Keep other-config/ keys in sync with device.ml:vif_udev_keys
 
-TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
-DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
-DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`
-
-XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}
-HOTPLUG=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}
-PRIVATE=/xapi/${DOMID}/private/${TYPE}/${DEVID}
 BRCTL=/usr/sbin/brctl
 IP=/sbin/ip
-
 
 handle_promiscuous()
 {
     local arg=$(xenstore-read "${PRIVATE}/other-config/promiscuous" 2>/dev/null)
     if [ $? -eq 0 -a -n "${arg}" ] ; then
         case "${arg}" in 
-            true|on) echo 1 > /sys/class/net/${vif}/brport/promisc ;;
-            *) echo 0 > /sys/class/net/${vif}/brport/promisc ;;
+            true|on) echo 1 > /sys/class/net/${dev}/brport/promisc ;;
+            *) echo 0 > /sys/class/net/${dev}/brport/promisc ;;
         esac
     fi
 }
@@ -48,9 +40,9 @@ handle_ethtool()
     local arg=$(xenstore-read "${PRIVATE}/other-config/ethtool-${opt}" 2>/dev/null)
     if [ $? -eq 0 -a -n "${arg}" ] ; then
         case "${arg}" in
-            true|on)   /sbin/ethtool -K "${vif}" "${opt}" on ;;
-            false|off) /sbin/ethtool -K "${vif}" "${opt}" off ;;
-            *) logger -t scripts-vif "Unknown ethtool argument ${opt}=${arg} on ${vif}/${VIFUUID}" ;;
+            true|on)   /sbin/ethtool -K "${dev}" "${opt}" on ;;
+            false|off) /sbin/ethtool -K "${dev}" "${opt}" off ;;
+            *) logger -t scripts-vif "Unknown ethtool argument ${opt}=${arg} on ${dev}/${VIFUUID}" ;;
         esac
     fi
 }
@@ -59,7 +51,7 @@ handle_mtu()
 {
     local mtu=$(xenstore-read "${PRIVATE}/MTU" 2>/dev/null)
     if [ $? -eq 0 -a -n "${mtu}" ]; then
-	echo "${mtu}" > /sys/class/net/${vif}/mtu
+	echo "${mtu}" > /sys/class/net/${dev}/mtu
     fi
 }
 
@@ -75,42 +67,76 @@ add_to_bridge()
 	logger -t scripts-vif "Failed to read ${PRIVATE}/bridge from xenstore"
 	exit 1
     fi
-    logger -t scripts-vif "Adding ${vif} to ${bridge} with address ${address}"
+    logger -t scripts-vif "Adding ${dev} to ${bridge} with address ${address}"
 
-    ${IP} link set "${vif}" down                        || logger -t scripts-vif "Failed to ip link set ${vif} down"
-    ${IP} link set "${vif}" arp off                     || logger -t scripts-vif "Failed to ip link set ${vif} arp off"
-    ${IP} link set "${vif}" multicast off               || logger -t scripts-vif "Failed to ip link set ${vif} multicast off"
-    ${IP} link set "${vif}" address "${address}"        || logger -t scripts-vif "Failed to ip link set ${vif} address ${address}"
-    ${IP} addr flush "${vif}"                           || logger -t scripts-vif "Failed to ip addr flush ${vif}"
+    ${IP} link set "${dev}" down                        || logger -t scripts-vif "Failed to ip link set ${dev} down"
+    ${IP} link set "${dev}" arp off                     || logger -t scripts-vif "Failed to ip link set ${dev} arp off"
+    ${IP} link set "${dev}" multicast off               || logger -t scripts-vif "Failed to ip link set ${dev} multicast off"
+    ${IP} link set "${dev}" address "${address}"        || logger -t scripts-vif "Failed to ip link set ${dev} address ${address}"
+    ${IP} addr flush "${dev}"                           || logger -t scripts-vif "Failed to ip addr flush ${dev}"
 
 
     ${BRCTL} setfd "${bridge}" 0                        || logger -t scripts-vif "Failed to brctl setfd ${bridge} 0"
-    ${BRCTL} addif "${bridge}" "${vif}"                 || logger -t scripts-vif "Failed to brctl addif ${bridge} ${vif}"
-    ${IP} link set "${vif}" up                          || logger -t scripts-vif "Failed to ip link set ${vif} up"
+    ${BRCTL} addif "${bridge}" "${dev}"                 || logger -t scripts-vif "Failed to brctl addif ${bridge} ${dev}"
+    ${IP} link set "${dev}" up                          || logger -t scripts-vif "Failed to ip link set ${dev} up"
 }
 
+type=$2
+
+case ${type} in
+    vif)
+	DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
+	DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`
+	dev=vif${DOMID}.${DEVID}
+	;;
+    tap)
+	dev=$INTERFACE
+	DOMID=`echo ${dev#tap} | cut -f 1 -d '.'`
+	DEVID=`echo ${dev#tap} | cut -f 2 -d '.'`
+	;;
+    *)  
+	logger -t scripts-vif "unknown interface type ${type}"
+	exit 1
+	;;
+esac
+
+XAPI=/xapi/${DOMID}/hotplug/vif/${DEVID}
+HOTPLUG=/xapi/${DOMID}/hotplug/vif/${DEVID}
+PRIVATE=/xapi/${DOMID}/private/vif/${DEVID}
+
+echo Called as "$@" "$DOMID" "$DEVID" | logger -t scripts-vif
 case "$1" in
 online)
-	handle_ethtool rx
-	handle_ethtool tx
-	handle_ethtool sg
-	handle_ethtool tso
-	handle_ethtool ufo
-	handle_ethtool gso
+	if [ "${type}" = "vif" ] ; then
+	    handle_ethtool rx
+	    handle_ethtool tx
+	    handle_ethtool sg
+	    handle_ethtool tso
+	    handle_ethtool ufo
+	    handle_ethtool gso
 
-	handle_mtu
-	add_to_bridge
-	handle_promiscuous
+	    handle_mtu
+	    add_to_bridge
+	    handle_promiscuous
 
-	xenstore-write "${HOTPLUG}/vif" "${vif}"
-	xenstore-write "${HOTPLUG}/hotplug" "online"
+	    xenstore-write "${HOTPLUG}/vif" "${dev}"
+	    xenstore-write "${HOTPLUG}/hotplug" "online"
 
-	# xs-xen.pq.hq:91e986b8e49f netback-wait-for-hotplug
-	xenstore-write "/local/domain/0/backend/vif/${DOMID}/${DEVID}/hotplug-status" "connected"
-
+	    # xs-xen.pq.hq:91e986b8e49f netback-wait-for-hotplug
+	    xenstore-write "/local/domain/0/backend/vif/${DOMID}/${DEVID}/hotplug-status" "connected"
+	fi
 	;;
+
+add)
+	if [ "${type}" = "tap" ] ; then
+	    add_to_bridge
+	fi
+	;;
+
 remove)
-	xenstore-rm "${HOTPLUG}/hotplug"
-	logger -t scripts-vif "vif${DOMID}.${DEVID} has been removed"
+	if [ "${type}" = "vif" ] ;then
+	    xenstore-rm "${HOTPLUG}/hotplug"
+	fi
+	logger -t scripts-vif "${dev} has been removed"
 	;;
 esac
