vif script: look for bridge in backend/vif/<domid>/<devid>/bridge first
This is where libxl puts it. We fall back to the "private" location if not
there.

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

diff --git a/scripts/vif-real b/scripts/vif-real
--- a/scripts/vif-real
+++ b/scripts/vif-real
@@ -165,12 +165,18 @@ add_to_bridge()
         xenstore-write "${HOTPLUG_ERROR}" "Failed to read ${PRIVATE}/bridge-MAC from xenstore"
         exit 1
     fi
-    local bridge=$(xenstore-read "${PRIVATE}/bridge")
+
+    local bridge=$(xenstore-read "backend/vif/$DOMID/$DEVID/bridge")
     if [ $? -ne 0 -o -z "${bridge}" ]; then
-        logger -t scripts-vif "Failed to read ${PRIVATE}/bridge from xenstore"
-        xenstore-write "${HOTPLUG_ERROR}" "Failed to read ${PRIVATE}/bridge from xenstore"
-        exit 1
+        logger -t scripts-vif "Failed to read backend/vif/$DOMID/$DEVID/bridge from xenstore. Trying ${PRIVATE}/bridge"
+        local bridge=$(xenstore-read "${PRIVATE}/bridge")
+        if [ $? -ne 0 -o -z "${bridge}" ]; then
+            logger -t scripts-vif "Failed to read ${PRIVATE}/bridge from xenstore"
+            xenstore-write "${HOTPLUG_ERROR}" "Failed to read ${PRIVATE}/bridge from xenstore"
+            exit 1
+        fi
     fi
+
     logger -t scripts-vif "Adding ${dev} to ${bridge} with address ${address}"
 
     ${IP} link set "${dev}" down                        || logger -t scripts-vif "Failed to ip link set ${dev} down"
