CP-18476: setup-pvs-proxy-rules update
Adds a rule to the setup-pvs-proxy-rules script to drop packets that come in on
a port from a PVS-proxied VM if the source IP is of a known PVS server.

These rules are based on the in_port and need to therefore be done for vif and
tap devices separately. To this end, two new arguments are added to the script:
for the "type" (vif or tap) and the interface name. The vif-real hotplug script
is updated to call setup-pvs-proxy-rules for both types, but to avoid
conflicts, it will only add or remove the rules that do not depend on the
in_port when the script is called with type=vif (because a vif device always
exists, and a tap may or may not).

The patch also renames some variables and updates comments to be a little
clearer.

Finally, vif-real is update to only call setup-pvs-proxy-rules if the
pvs-interface xenstore node exists.

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

diff --git a/scripts/vif-real b/scripts/vif-real
--- a/scripts/vif-real
+++ b/scripts/vif-real
@@ -191,9 +191,12 @@ add_to_bridge()
         ;;
     esac
 
-    if [ "${TYPE}" = "vif" ] ; then
+    # PVS proxy rules are only setup if the pvs-interface xenstore node exists
+    xenstore-read ${PRIVATE}/pvs-interface 2>/dev/null
+    if [ $? -eq 0 ]; then
         local setup_pvs_proxy_rules=$(xenstore-read "${PRIVATE}/setup-pvs-proxy-rules" 2>/dev/null)
-        $setup_pvs_proxy_rules add "$PRIVATE" || logger -t scripts-vif "Failed to $setup_pvs_proxy_rules add $PRIVATE"
+        $setup_pvs_proxy_rules add "${TYPE}" "${dev}" "$PRIVATE" \
+            || logger -t scripts-vif "Failed to ${setup_pvs_proxy_rules} add ${TYPE} ${dev} ${PRIVATE}"
 	fi
 
     local setup_vif_rules=$(xenstore-read "${PRIVATE}/setup-vif-rules" 2>/dev/null)
@@ -204,9 +207,12 @@ remove_from_bridge()
 {
     ${IP} link set "${dev}" down || logger -t scripts-vif "Failed to ip link set ${dev} down"
 
-    if [ "${TYPE}" = "vif" ] ; then
+    # PVS proxy rules are only setup if the pvs-interface xenstore node exists
+    xenstore-read ${PRIVATE}/pvs-interface 2>/dev/null
+    if [ $? -eq 0 ]; then
         local setup_pvs_proxy_rules=$(xenstore-read "${PRIVATE}/setup-pvs-proxy-rules" 2>/dev/null)
-        /usr/libexec/xenopsd/setup-pvs-proxy-rules remove "$PRIVATE" || logger -t scripts-vif "Failed to $setup_pvs_proxy_rules remove $PRIVATE"
+        /usr/libexec/xenopsd/setup-pvs-proxy-rules remove "${TYPE}" "${dev}" "${PRIVATE}" \
+            || logger -t scripts-vif "Failed to ${setup_pvs_proxy_rules} remove ${TYPE} ${dev} ${PRIVATE}"
     fi
 
     local setup_vif_rules=$(xenstore-read "${PRIVATE}/setup-vif-rules" 2>/dev/null)
