Using Syslog_stdout for logging Signed-off-by: Siddharth Vinothkumar <siddharth.vinothkumar@citrix.com>

diff --git a/scripts/xe-toolstack-restart b/scripts/xe-toolstack-restart
--- a/scripts/xe-toolstack-restart
+++ b/scripts/xe-toolstack-restart
@@ -11,11 +11,13 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
+FILENAME=`basename $0`
 LOCKFILE='/dev/shm/xe_toolstack_restart.lock'
 
 (
 flock -x -n 200
-if [ "$?" != 0 ]; then echo "Exiting: cannot lock $LOCKFILE. Is an instance $0 running already?"; exit 1; fi
+if [ "$?" != 0 ]; then echo "Exiting: cannot lock $LOCKFILE. Is an instance of $0 running already?"; exit 1; fi
+echo "Executing $FILENAME"
 
 POOLCONF=`cat @ETCDIR@/pool.conf`
 
