CA-103101: Create a background process from restart_agent to restart the entire toolstack. Signed-off-by: Siddharth Vinothkumar <siddharth.vinothkumar@citrix.com>

diff --git a/scripts/xe-toolstack-restart b/scripts/xe-toolstack-restart
--- a/scripts/xe-toolstack-restart
+++ b/scripts/xe-toolstack-restart
@@ -11,6 +11,11 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU Lesser General Public License for more details.
 #
+LOCKFILE='/dev/shm/xe_toolstack_restart.lock'
+
+(
+flock -x -n 200
+if [ "$?" != 0 ]; then echo "Exiting: cannot lock $LOCKFILE. Is an instance $0 running already?"; exit 1; fi
 
 POOLCONF=`cat @ETCDIR@/pool.conf`
 
@@ -41,4 +46,9 @@ service perfmon start
 service squeezed start
 service v6d start
 service xapi start
+
+rm -f $LOCKFILE
 echo "done."
+)200>$LOCKFILE
+
+exit $?
