CA-326349 Kill stunnel processes on restart
Restarting stunnel fixes an issue where a slave
was seen to be holding port 80 in use, which was
stopping the pool master from connecting.

Signed-off-by: lippirk <ben.anson@citrix.com>

diff --git a/scripts/xe-toolstack-restart b/scripts/xe-toolstack-restart
--- a/scripts/xe-toolstack-restart
+++ b/scripts/xe-toolstack-restart
@@ -32,6 +32,16 @@ SERVICES="perfmon xapi v6d xenopsd xenopsd-xc xenopsd-xenlight
   xcp-rrdd-xenpm xcp-rrdd-gpumon xcp-rrdd xcp-networkd squeezed forkexecd
   $MPATHALERT xapi-storage-script xapi-clusterd varstored-guard message-switch"
 
+tmp_file=$(mktemp --suffix="xe-toolstack-restart")
+/opt/xensource/libexec/xapissl stop > $tmp_file 2>&1
+kill_stunnel_exit_code=$?
+if [[ $kill_stunnel_exit_code != 0 ]]; then
+  printf "\nFailed to kill stunnel processes! Output:\n"
+  cat $tmp_file
+  printf "\n"
+fi
+rm -f $tmp_file
+
 TO_RESTART=""
 for svc in $SERVICES ; do
 	# restart services only if systemd said they were enabled
